######################################################################
# Automatically generated by qmake (3.0) mar. nov. 8 13:19:33 2016
######################################################################

TEMPLATE = app
TARGET = cpp_babel
INCLUDEPATH += .
QT += widgets network

FORMS += mainwindow.ui loginwindow.ui

# Input
HEADERS += CommandManager.hpp ServerEndpoint.hpp Babel.hpp MainWindow.hpp LoginWindow.hpp ClientConnection.hpp
SOURCES += CommandManager.cpp main.cpp ServerEndpoint.cpp Babel.cpp MainWindow.cpp LoginWindow.cpp ClientConnection.cpp
